In [1]:
import os
import pandas as pd

In [2]:
all_path = os.listdir('./data11/')

In [3]:
all_path

['거제_강수_수온_기온(17_22).csv',
 '거제_강수_일조_풍속(17_22).csv',
 '통영_강수_수온_기온(17_22).csv',
 '통영_강수_일조_풍속(17_22).csv']

In [13]:
df= pd.DataFrame({'일시': pd.date_range('2017-01-01', '2022-09-30', freq='D')})
df['일시'] = df['일시'].astype('str')
df.set_index('일시', inplace=True)

for file in all_path:
    all=pd.read_csv('./data11/'+file, encoding='cp949')
    all.set_index('일시', inplace=True)
    df=pd.concat([df, all], axis=1)

In [14]:
df.columns

Index(['지점', '평균 풍속(m/s)', '평균 상대습도(%)', '평균 기온(°C)', '평균 수온(°C)', '지점',
       '일강수량(mm)', '합계 일조시간(hr)', '지점', '평균 풍속(m/s)', '평균 상대습도(%)',
       '평균 기온(°C)', '평균 수온(°C)', '지점', '일강수량(mm)', '합계 일조시간(hr)'],
      dtype='object')

In [15]:
# df['지점'] = df['지점'].astype(str)

In [16]:
df

,지점,평균 풍속(m/s),평균 상대습도(%),평균 기온(°C),평균 수온(°C),지점,일강수량(mm),합계 일조시간(hr),지점,평균 풍속(m/s),평균 상대습도(%),평균 기온(°C),평균 수온(°C),지점,일강수량(mm),합계 일조시간(hr)
일시,,,,,,,,,,,,,,,,
2017-01-01,거제,3.3,60.0,9.8,15.3,거제,NaN,7.0,통영,NaN,62.0,9.4,17.3,통영,NaN,8.6
2017-01-02,거제,5.1,66.0,12.0,15.4,거제,NaN,6.5,통영,NaN,65.0,12.0,16.8,통영,NaN,6.9
2017-01-03,거제,4.6,53.0,10.8,15.0,거제,NaN,7.3,통영,4.8,58.0,9.6,15.3,통영,NaN,8.7
2017-01-04,거제,5.2,54.0,11.3,15.6,거제,NaN,6.5,통영,4.2,49.0,10.5,13.9,통영,NaN,7.7
2017-01-05,거제,10.0,72.0,11.8,NaN,거제,NaN,0.9,통영,8.9,68.0,11.1,13.8,통영,NaN,2.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-09-26,거제,5.7,78.0,22.6,23.8,거제,0.0,0.2,NaN,NaN,NaN,NaN,NaN,통영,0.0,0.7
2022-09-27,거제,7.4,82.0,23.0,24.4,거제,0.1,3.5,NaN,NaN,NaN,NaN,NaN,통영,0.1,5.7
2022-09-28,거제,4.7,78.0,23.2,24.3,거제,NaN,3.7,NaN,NaN,NaN,NaN,NaN,통영,NaN,4.5
2022-09-29,거제,2.8,75.0,23.4,23.9,거제,NaN,10.4,NaN,NaN,NaN,NaN,NaN,통영,NaN,9.7
2022-09-30,거제,2.5,80.0,23.1,24.0,거제,NaN,10.4,NaN,NaN,NaN,NaN,NaN,통영,NaN,9.7

In [17]:
df.isnull().sum()

지점               93
평균 풍속(m/s)      113
평균 상대습도(%)      173
평균 기온(°C)       179
평균 수온(°C)       112
지점                0
일강수량(mm)       1482
합계 일조시간(hr)       2
지점               58
평균 풍속(m/s)      101
평균 상대습도(%)      114
평균 기온(°C)        61
평균 수온(°C)        65
지점                0
일강수량(mm)       1413
합계 일조시간(hr)       8
dtype: int64

In [ ]:
df.to_csv('beach.csv')

In [9]:
# df= pd.DataFrame()
# for file in all_path:
#     all=pd.read_csv('./data11/'+file, encoding='cp949')
#     df=pd.concat([df, all], ignore_index=True)

In [10]:
# df['지점'].replace('22104', '거제', inplace=True)
# df['지점'].replace('294', '거제', inplace=True)
# df['지점'].replace('162', '통영', inplace=True)
# df['지점'].replace('22188', '통영', inplace=True)

In [11]:
# df.drop(['평균기압(hPa)','평균 상대습도(%)','지점명','평균기온(°C)','최저기온(°C)',
#          '최고기온 시각(hhmi)','최저기온 시각(hhmi)','최고기온(°C)','합계 일사량(MJ/m2)'],
#        axis=1, inplace=True)