In [24]:
import pandas as pd

In [25]:
DIR1='./l.csv'
DIR2='./m.csv'
DIR3='./n.csv'
DIR4='./o.csv'
DIR5='./p.csv'
DIR6='./q.csv'

In [26]:
df1=pd.read_csv(DIR1, header=None)
df2=pd.read_csv(DIR2, header=None)
df3=pd.read_csv(DIR3, header=None)
df4=pd.read_csv(DIR4, header=None)
df5=pd.read_csv(DIR5, header=None)
df6=pd.read_csv(DIR6, header=None)

C:\Users\USER\AppData\Local\Temp\ipykernel_14648\2332636513.py:6: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df6=pd.read_csv(DIR6, header=None)

In [27]:
df1.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,low limit,2,2,20,0.5,0.5,0.5,0,-0.8,-0.8,...,0,30,30,30,30,0.01,-3,0.01,-0.5,-0.5
1,high limit,15,15,120,12,52,4550,2,-0.35,-0.35,...,3,50,50,50,50,3.5,-0.01,14,4,4
2,barcode,LB,LC,LD,LE,LF,LG,LH,LI,LJ,...,LAP,LAQ,LAR,LAS,LAT,LAU,LAV,LAW,LAX,LAY
3,module3706,9.196217537,8.742083549,55.51790619,6.483315468,18.27116203,122.4462509,0.040400144,-0.413626343,-0.414065927,...,1.700554951,43.36001934,42.27314447,43.97369942,43.436909,1.142403369,-0.905727436,3.973639329,0.720036149,0.532084167
4,module1,9.309750557,9.196217537,54.26903534,6.483315468,16.7976799,133.4973602,0.038925223,-0.425934047,-0.427692294,...,1.035262127,43.28350988,42.39583566,43.07134107,42.24824775,1.155936156,-0.799745143,3.21339478,0.503312051,0.661879301

In [28]:
df2.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,low limit,-0.5,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,4,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,MB,MC,MD,ME,MF,MG,MH,MI,MJ,...,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU
3,module274,0.901858926,1.649712443,1.63025558,1.623497128,1.632140636,1.635928512,1.621284842,1.601390004,1.576812387,...,1.607282877,1.613696456,1.629662514,1.628187656,1.617716908,1.613705993,1.614355087,1.622731447,1.601292968,1.622177839
4,module3298,0.92304343,1.641934037,1.627681017,1.633938074,1.660049081,1.680953503,1.687386513,1.668748379,1.648342133,...,1.607692719,1.627216816,1.657950163,1.675144911,1.687854886,1.680534005,1.682374239,1.611142874,1.606105685,1.638592243

In [29]:
df3.head()

,0,1,2,3,4,5,6,7,8,9,...,31,32,33,34,35,36,37,38,39,40
0,low limit,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,NB,NC,ND,NE,NF,NG,NH,NI,NJ,...,NAF,NAG,NAH,NAI,NAJ,NAK,NAL,NAM,NAN,NAO
3,module8862,1.678077698,1.654353976,1.634274721,1.640864372,1.670669436,1.644556165,1.63746655,1.671719074,1.684547305,...,1.62649107,1.644100666,1.662058353,1.655901551,1.650413513,1.646280527,1.655600786,1.647045493,1.633630514,1.640711784
4,module443,1.651376009,1.644402027,1.63298583,1.637390971,1.662315845,1.617227554,1.59920609,1.632731915,1.657195568,...,1.596427917,1.607979894,1.637476325,1.646760464,1.643029332,1.638683796,1.644470096,1.630109429,1.608395934,1.607437491

In [30]:
df4.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,low limit,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,OB,OC,OD,OE,OF,OG,OH,OI,OJ,...,OAZ,OBA,OBB,OBC,OBD,OBE,OBF,OBG,OBH,OBI
3,module789,1.642542005,1.643992543,1.636243224,1.621706367,1.600087404,1.577953696,1.596674085,1.614463329,1.620817304,...,1.60476923,1.588495612,1.608421922,1.628622055,1.618224144,1.619284391,1.624693036,1.618678808,1.604282737,1.596675634
4,module4192,1.652584672,1.66634798,1.661535382,1.646724701,1.637596369,1.580028653,1.596682191,1.607276559,1.608465075,...,1.562722087,1.544186831,1.56231606,1.593993187,1.590831041,1.598883033,1.598778844,1.580049992,1.551323295,1.550339818

In [31]:
df5.head()

,0,1,2,3,4,5,6,7,8,9,...,41,42,43,44,45,46,47,48,49,50
0,low limit,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,PB,PC,PD,PE,PF,PG,PH,PI,PJ,...,PAP,PAQ,PAR,PAS,PAT,PAU,PAV,PAW,PAX,PAY
3,module3158,1.597673178,1.596551418,1.611853361,1.623739481,1.626957178,1.609759212,1.599552751,1.60321784,1.619698644,...,1.631358743,1.644104719,1.635082006,1.62251544,1.625540376,1.627163172,1.633051276,1.645643592,1.648587823,1.643083453
4,module9101,1.587428927,1.608364224,1.611225605,1.619310737,1.619567394,1.600398183,1.584273577,1.58857286,1.605104208,...,1.627970099,1.645436764,1.643384457,1.626332402,1.62373054,1.620441556,1.63503778,1.649520993,1.64633882,1.654895067

In [32]:
df6.head()

,0,1,2,3,4,5,6,7,8,9,...,61,62,63,64,65,66,67,68,69,70
0,low limit,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,QB,QC,QD,QE,QF,QG,QH,QI,QJ,...,QBJ,QBK,QBL,QBM,QBN,QBO,QBP,QBQ,QBR,QBS
3,module9138,1.68803072,1.671784759,1.659208536,1.663386583,1.675576568,1.702787757,1.703445673,1.705212355,1.716116428,...,1.644232869,1.638100624,1.637249351,1.604166627,1.600101471,1.613740683,1.629603982,1.629444599,1.620921731,1.603893161
4,module9122,1.703558803,1.679965258,1.671675682,1.672392011,1.690542102,1.712445974,1.708434224,1.721238613,1.736963987,...,1.595143795,1.59408021,1.593248487,1.570883632,1.558725238,1.570076942,1.577320218,1.575303555,1.568512797,1.558322787

In [33]:
df1.drop_duplicates(subset=0, keep='last', inplace=True)
df2.drop_duplicates(subset=0, keep='last', inplace=True)
df3.drop_duplicates(subset=0, keep='last', inplace=True)
df4.drop_duplicates(subset=0, keep='last', inplace=True)
df5.drop_duplicates(subset=0, keep='last', inplace=True)
df6.drop_duplicates(subset=0, keep='last', inplace=True)

In [34]:
# 1. Log 파일 합치기
dfall=pd.concat([df1,df2,df3,df4,df5,df6], ignore_index= 'bool', join='inner', axis=1)

In [35]:
dfall

,0,1,2,3,4,5,6,7,8,9,...,286,287,288,289,290,291,292,293,294,295
0,low limit,2,2,20,0.5,0.5,0.5,0,-0.8,-0.8,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
1,high limit,15,15,120,12,52,4550,2,-0.35,-0.35,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
2,barcode,LB,LC,LD,LE,LF,LG,LH,LI,LJ,...,QBJ,QBK,QBL,QBM,QBN,QBO,QBP,QBQ,QBR,QBS
137,module47,9.082683563,8.287948608,53.5878334,6.483315468,16.502985,130.6977386,0.035892896,-0.422417551,-0.41934064,...,1.604371548,1.59091413,1.588540912,1.590088129,1.588909984,1.589444518,1.594468713,1.59008038,1.579930663,1.568837285
300,module116,9.650351524,9.196217537,55.17730331,5.599226952,16.7976799,134.2341003,0.033359338,-0.425494492,-0.422417551,...,1.560780048,1.547827482,1.548163056,1.535196304,1.530202866,1.542817473,1.547331214,1.541668773,1.526836276,1.515796542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6425,module3459,9.763885498,9.650351524,59.83218002,5.893922806,16.94502831,138.654541,0.03130503,-0.418461531,-0.419780225,...,1.638633132,1.628851771,1.632206082,1.610855341,1.607432723,1.617700577,1.621624589,1.623884439,1.612363935,1.608065605
6427,module3461,9.536818504,10.33155251,53.36076736,6.04127121,17.09237671,169.4502869,0.002361101,-0.421098888,-0.420219749,...,1.637022257,1.630612969,1.624907374,1.630019307,1.627528191,1.62836647,1.630693436,1.629782438,1.620449424,1.617116928
6428,module3462,9.763885498,9.763885498,55.40437317,6.335967064,17.82911682,207.9081421,0.043896869,-0.414945036,-0.41538462,...,1.607001781,1.600141287,1.601732969,1.596524119,1.592435598,1.599380016,1.596749425,1.594390035,1.60252142,1.607660174
6435,module3467,8.969150543,9.650351524,57.22090912,6.335967064,17.38707352,248.1341553,0.050151289,-0.419780225,-0.419780225,...,1.595640182,1.582312584,1.584113955,1.572246909,1.572929978,1.583353281,1.587872028,1.583806992,1.579763174,1.575294375
6443,module3471,9.423284531,9.423284531,54.95023727,6.483315468,18.27116203,136.8863678,0.053049207,-0.41538462,-0.417582422,...,1.615917921,1.604914308,1.592167974,1.602792263,1.601650715,1.602130771,1.604994416,1.600344539,1.588847518,1.574067473

In [38]:
dfall[0].unique()

array(['low limit', 'high limit', 'barcode', 'module47', 'module116',
       'module128', 'module163', 'module169', 'module252', 'module262',
       'module301', 'module302', 'module388', 'module411', 'module451',
       'module458', 'module553', 'module583', 'module711', 'module717',
       'module749', 'module819', 'module831', 'module832', 'module856',
       'module886', 'module892', 'module902', 'module964', 'module980',
       'module992', 'module999', 'module1012', 'module1017', 'module1034',
       'module1050', 'module1077', 'module1112', 'module1114',
       'module1124', 'module1186', 'module1214', 'module1221',
       'module1255', 'module1260', 'module1263', 'module1283',
       'module1285', 'module1288', 'module1290', 'module1306',
       'module1307', 'module1329', 'module1340', 'module1345',
       'module1377', 'module1386', 'module1428', 'module1443',
       'module1445', 'module1474', 'module1493', 'module1508',
       'module1510', 'module1513', 'module1514', 'module1515',
       'module1517', 'module1529', 'module1531', 'module1533',
       'module1536', 'module1564', 'module1569', 'module1586',
       'module1595', 'module1618', 'module1634', 'module1638',
       'module1647', 'module1652', 'module1662', 'module1664',
       'module1672', 'module1694', 'module1697', 'module1721',
       'module1739', 'module1755', 'module1757', 'module1765',
       'module1779', 'module1790', 'module1794', 'module1820',
       'module1824', 'module1837', 'module1839', 'module1847',
       'module1850', 'module1858', 'module1873', 'module1882',
       'module1884', 'module1886', 'module1895', 'module1911',
       'module1924', 'module1925', 'module1928', 'module1933',
       'module1935', 'module1936', 'module1942', 'module1952',
       'module1956', 'module1957', 'module1971', 'module1977',
       'module1992', 'module2004', 'module2014', 'module2020',
       'module2031', 'module2038', 'module2063', 'module2072',
       'module2075', 'module2076', 'module2080', 'module2098',
       'module2115', 'module2125', 'module2135', 'module2153',
       'module2157', 'module2161', 'module2194', 'module2198',
       'module2201', 'module2204', 'module2210', 'module2211',
       'module2215', 'module2217', 'module2218', 'module2234',
       'module2236', 'module2238', 'module2247', 'module2250',
       'module2255', 'module2266', 'module2284', 'module2288',
       'module2293', 'module2296', 'module2299', 'module2301',
       'module2302', 'module2307', 'module2309', 'module2326',
       'module2332', 'module2334', 'module2337', 'module2347',
       'module2349', 'module2358', 'module2359', 'module2362',
       'module2363', 'module2369', 'module2371', 'module2377',
       'module2387', 'module2392', 'module2393', 'module2408',
       'module2412', 'module2415', 'module2416', 'module2417',
       'module2423', 'module2435', 'module2438', 'module2444',
       'module2445', 'module2447', 'module2461', 'module2462',
       'module2467', 'module2473', 'module2474', 'module2477',
       'module2481', 'module2482', 'module2484', 'module2496',
       'module2516', 'module2528', 'module2529', 'module2534',
       'module2539', 'module2543', 'module2545', 'module2553',
       'module2555', 'module2559', 'module2561', 'module2568',
       'module2570', 'module2571', 'module2572', 'module2576',
       'module2579', 'module2595', 'module2597', 'module2602',
       'module2605', 'module2610', 'module2611', 'module2612',
       'module2615', 'module2616', 'module2620', 'module2621',
       'module2629', 'module2635', 'module2647', 'module2648',
       'module2650', 'module2653', 'module2670', 'module2673',
       'module2676', 'module2678', 'module2680', 'module2682',
       'module2688', 'module2693', 'module2695', 'module2697',
       'module2704', 'module2707', 'module2708', 'module2711',
       'module2714', 'module2716', 'module2737', 'module2743',
       'module2744', 'module2747', 'module2748', 'module2753',
       'module2754', 'module2756', 'module2759', 'module2762',
       'module2764', 'module2765', 'module2766', 'module2773',
       'module2775', 'module2776', 'module2789', 'module2792',
       'module2794', 'module2795', 'module2810', 'module2815',
       'module2817', 'module2820', 'module2821', 'module2822',
       'module2826', 'module2852', 'module2853', 'module2854',
       'module2858', 'module2862', 'module2866', 'module2869',
       'module2870', 'module2872', 'module2875', 'module2876',
       'module2879', 'module2880', 'module2884', 'module2889',
       'module2892', 'module2908', 'module2909', 'module2911',
       'module2915', 'module2918', 'module2923', 'module2924',
       'module2925', 'module2928', 'module2929', 'module2930',
       'module2932', 'module2938', 'module2941', 'module2942',
       'module2946', 'module2953', 'module2957', 'module2962',
       'module2963', 'module2964', 'module2968', 'module2969',
       'module2974', 'module2978', 'module2981', 'module2985',
       'module2986', 'module2987', 'module2989', 'module2991',
       'module2996', 'module2998', 'module2999', 'module3002',
       'module3006', 'module3010', 'module3013', 'module3017',
       'module3019', 'module3021', 'module3022', 'module3023',
       'module3024', 'module3026', 'module3028', 'module3032',
       'module3036', 'module3040', 'module3043', 'module3049',
       'module3052', 'module3058', 'module3060', 'module3063',
       'module3065', 'module3066', 'module3072', 'module3075',
       'module3076', 'module3081', 'module3085', 'module3086',
       'module3090', 'module3098', 'module3103', 'module3106',
       'module3114', 'module3115', 'module3120', 'module3122',
       'module3124', 'module3127', 'module3130', 'module3131',
       'module3140', 'module3141', 'module3142', 'module3143',
       'module3146', 'module3148', 'module3155', 'module3157',
       'module3158', 'module3159', 'module3162', 'module3163',
       'module3165', 'module3167', 'module3179', 'module3180',
       'module3184', 'module3187', 'module3191', 'module3192',
       'module3198', 'module3200', 'module3202', 'module3205',
       'module3211', 'module3214', 'module3215', 'module3216',
       'module3221', 'module3222', 'module3224', 'module3226',
       'module3230', 'module3232', 'module3238', 'module3239',
       'module3241', 'module3246', 'module3247', 'module3250',
       'module3260', 'module3262', 'module3267', 'module3272',
       'module3273', 'module3277', 'module3284', 'module3288',
       'module3290', 'module3291', 'module3296', 'module3297',
       'module3298', 'module3302', 'module3311', 'module3312',
       'module3318', 'module3321', 'module3322', 'module3323',
       'module3325', 'module3327', 'module3333', 'module3336',
       'module3339', 'module3340', 'module3343', 'module3346',
       'module3347', 'module3349', 'module3350', 'module3352',
       'module3353', 'module3355', 'module3356', 'module3357',
       'module3358', 'module3362', 'module3363', 'module3364',
       'module3368', 'module3372', 'module3373', 'module3377',
       'module3383', 'module3385', 'module3387', 'module3389',
       'module3392', 'module3393', 'module3395', 'module3397',
       'module3398', 'module3401', 'module3408', 'module3409',
       'module3414', 'module3418', 'module3421', 'module3422',
       'module3425', 'module3429', 'module3431', 'module3433',
       'module3437', 'module3438', 'module3440', 'module3442',
       'module3443', 'module3444', 'module3445', 'module3446',
       'module3448', 'module3453', 'module3454', 'module3458',
       'module3459', 'module3461', 'module3462', 'module3467',
       'module3471'], dtype=object)

In [14]:
# 2. Log들을 바코드 순(사전 순)으로 정렬
dfall=dfall.sort_values([0], ascending=True)

In [15]:
dfall=dfall.set_index(0)

In [16]:
dfall

,1,2,3,4,5,6,7,8,9,10,...,286,287,288,289,290,291,292,293,294,295
0,,,,,,,,,,,,,,,,,,,,,
barcode,LB,LC,LD,LE,LF,LG,LH,LI,LJ,LK,...,QBJ,QBK,QBL,QBM,QBN,QBO,QBP,QBQ,QBR,QBS
high limit,15,15,120,12,52,4550,2,-0.35,-0.35,-0.18,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
low limit,2,2,20,0.5,0.5,0.5,0,-0.8,-0.8,-0.5,...,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05,1.05
module1012,9.763885498,9.196217537,50.9765625,6.04127121,17.68176842,92.82928467,0.040737174,-0.413626343,-0.412747234,-0.225934058,...,1.570769072,1.561062336,1.56181705,1.54428184,1.544676781,1.551813841,1.549749494,1.55190599,1.546622753,1.534638643
module1017,9.877418518,9.763885498,61.08105087,6.188619137,16.3556366,157.3677521,0.064685896,-0.418901086,-0.418461531,-0.232527465,...,1.575162649,1.572163105,1.569843531,1.534832358,1.534277916,1.547499418,1.549714565,1.550039053,1.537935734,1.529629707
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
module902,9.423284531,8.969150543,54.26903534,6.335967064,16.6503334,114.4894562,0.041803151,-0.428131849,-0.42725274,-0.236043945,...,1.598844767,1.593074203,1.598813772,1.561130643,1.554870725,1.565752506,1.572142005,1.572543383,1.568345189,1.556233406
module964,9.763885498,9.536818504,54.49610519,6.778011322,18.12381363,212.7706146,0.034307413,-0.41230768,-0.411428541,-0.229450539,...,1.655488491,1.636828899,1.639593244,1.662670612,1.647689819,1.652153015,1.651480198,1.645469666,1.644498348,1.637236714
module980,9.536818504,9.650351524,56.6532402,6.335967064,17.97646523,190.8157654,0.031269901,-0.413186818,-0.414505482,-0.23208791,...,1.652416706,1.64732039,1.65171802,1.643315554,1.631997466,1.640114069,1.648346543,1.640979409,1.626419663,1.614555955
module992,8.060881615,7.720281124,57.1073761,6.778011322,17.23972511,143.3696747,0.034850713,-0.42329669,-0.424615353,-0.235604391,...,1.634153485,1.620486856,1.614460588,1.60739255,1.609816194,1.623726249,1.626222372,1.622713327,1.614545345,1.599405766
module999,9.650351524,9.877418518,59.15097809,6.778011322,16.6503334,127.4560852,0.032210626,-0.410989016,-0.410989016,-0.235164836,...,1.633249521,1.626101613,1.622587085,1.619727254,1.621820807,1.627647161,1.627124906,1.624979734,1.61631453,1.60647583

In [17]:
dfall.isnull().sum()

1      0
2      0
3      0
4      0
5      0
      ..
291    0
292    0
293    0
294    0
295    0
Length: 295, dtype: int64

In [18]:
dfall.dtypes

1      object
2      object
3      object
4      object
5      object
        ...
291    object
292    object
293    object
294    object
295    object
Length: 295, dtype: object

In [19]:
dfall.iloc[1,:]

1       15
2       15
3      120
4       12
5       52
      ...
291    2.2
292    2.2
293    2.2
294    2.2
295    2.2
Name: high limit, Length: 295, dtype: object

In [20]:
dfall.iloc[0]

1       LB
2       LC
3       LD
4       LE
5       LF
      ...
291    QBO
292    QBP
293    QBQ
294    QBR
295    QBS
Name: barcode, Length: 295, dtype: object

In [22]:
# for i in range(1,4749):
#     dfall=dfall.iloc[i,:].astype(float)

# print(dfall)

In [ ]:
# dfall.iloc[1,0]

In [ ]:
# dfall.iloc[2,0]

In [ ]:
# dfall.iloc[3:,0].unique()

In [ ]:
# result_to_dict = {}

In [ ]:
# result1=[]
# for i in range(0,4749):
#     a = dfall.iloc[3:,i].unique()
#     if dfall.iloc[1,i] >= a >= dfall.iloc[2,i]:
#         pass
#     elif not dfall.iloc[1,i] >= a >= dfall.iloc[2,i]:
#         result1.append()