In [7]:
import pandas as pd

In [8]:
DIR1='./l.csv'
DIR2='./m.csv'
DIR3='./n.csv'
DIR4='./o.csv'
DIR5='./p.csv'
DIR6='./q.csv'

In [9]:
df1=pd.read_csv(DIR1)
df2=pd.read_csv(DIR2)
df3=pd.read_csv(DIR3)
df4=pd.read_csv(DIR4)
df5=pd.read_csv(DIR5)
df6=pd.read_csv(DIR6)

C:\Users\USER\AppData\Local\Temp\ipykernel_13396\3100844036.py:6: DtypeWarning: Columns (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70) have mixed types. Specify dtype option on import or set low_memory=False.
  df6=pd.read_csv(DIR6)

In [10]:
df1.head()

,low limit,2,2.1,20,0.5,0.5.1,0.5.2,0,-0.8,-0.8.1,...,0.2,30,30.1,30.2,30.3,0.01,-3,0.01.1,-0.5.6,-0.5.7
0,high limit,15,15,120,12,52,4550,2,-0.35,-0.35,...,3,50,50,50,50,3.5,-0.01,14,4,4
1,barcode,LB,LC,LD,LE,LF,LG,LH,LI,LJ,...,LAP,LAQ,LAR,LAS,LAT,LAU,LAV,LAW,LAX,LAY
2,module3706,9.196217537,8.742083549,55.51790619,6.483315468,18.27116203,122.4462509,0.040400144,-0.413626343,-0.414065927,...,1.700554951,43.36001934,42.27314447,43.97369942,43.436909,1.142403369,-0.905727436,3.973639329,0.720036149,0.532084167
3,module1,9.309750557,9.196217537,54.26903534,6.483315468,16.7976799,133.4973602,0.038925223,-0.425934047,-0.427692294,...,1.035262127,43.28350988,42.39583566,43.07134107,42.24824775,1.155936156,-0.799745143,3.21339478,0.503312051,0.661879301
4,module48,9.650351524,9.196217537,57.22090912,6.778011322,18.56585693,146.1692963,0.041497082,-0.410109878,-0.413186818,...,1.01853927,41.56215765,41.33630006,42.35483933,42.05014958,1.239297855,-0.953670429,2.366441218,0.990553558,0.594899654

In [11]:
df2.head()

,low limit,-0.5,1.05,1.05.1,1.05.2,1.05.3,1.05.4,1.05.5,1.05.6,1.05.7,...,1.05.9,1.05.10,1.05.11,1.05.12,1.05.13,1.05.14,1.05.15,1.05.16,1.05.17,1.05.18
0,high limit,4,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
1,barcode,MB,MC,MD,ME,MF,MG,MH,MI,MJ,...,ML,MM,MN,MO,MP,MQ,MR,MS,MT,MU
2,module274,0.901858926,1.649712443,1.63025558,1.623497128,1.632140636,1.635928512,1.621284842,1.601390004,1.576812387,...,1.607282877,1.613696456,1.629662514,1.628187656,1.617716908,1.613705993,1.614355087,1.622731447,1.601292968,1.622177839
3,module3298,0.92304343,1.641934037,1.627681017,1.633938074,1.660049081,1.680953503,1.687386513,1.668748379,1.648342133,...,1.607692719,1.627216816,1.657950163,1.675144911,1.687854886,1.680534005,1.682374239,1.611142874,1.606105685,1.638592243
4,module5893,0.786753953,1.648906112,1.633257627,1.630871654,1.638624668,1.640860319,1.63367784,1.614843488,1.598014593,...,1.617283702,1.625161529,1.640353441,1.640476704,1.63512373,1.632860184,1.632693529,1.627834678,1.610808969,1.630464315

In [12]:
df3.head()

,low limit,1.05,1.05.1,1.05.2,1.05.3,1.05.4,1.05.5,1.05.6,1.05.7,1.05.8,...,1.05.30,1.05.31,1.05.32,1.05.33,1.05.34,1.05.35,1.05.36,1.05.37,1.05.38,1.05.39
0,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
1,barcode,NB,NC,ND,NE,NF,NG,NH,NI,NJ,...,NAF,NAG,NAH,NAI,NAJ,NAK,NAL,NAM,NAN,NAO
2,module8862,1.678077698,1.654353976,1.634274721,1.640864372,1.670669436,1.644556165,1.63746655,1.671719074,1.684547305,...,1.62649107,1.644100666,1.662058353,1.655901551,1.650413513,1.646280527,1.655600786,1.647045493,1.633630514,1.640711784
3,module443,1.651376009,1.644402027,1.63298583,1.637390971,1.662315845,1.617227554,1.59920609,1.632731915,1.657195568,...,1.596427917,1.607979894,1.637476325,1.646760464,1.643029332,1.638683796,1.644470096,1.630109429,1.608395934,1.607437491
4,module6105,1.657915711,1.638933063,1.619235158,1.63408041,1.669029236,1.6209445,1.614417553,1.64669466,1.666098595,...,1.6150105,1.627382755,1.64728868,1.644554019,1.634436965,1.627096057,1.630097985,1.640401006,1.62874949,1.630639672

In [13]:
df4.head()

,low limit,1.05,1.05.1,1.05.2,1.05.3,1.05.4,1.05.5,1.05.6,1.05.7,1.05.8,...,1.05.50,1.05.51,1.05.52,1.05.53,1.05.54,1.05.55,1.05.56,1.05.57,1.05.58,1.05.59
0,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
1,barcode,OB,OC,OD,OE,OF,OG,OH,OI,OJ,...,OAZ,OBA,OBB,OBC,OBD,OBE,OBF,OBG,OBH,OBI
2,module789,1.642542005,1.643992543,1.636243224,1.621706367,1.600087404,1.577953696,1.596674085,1.614463329,1.620817304,...,1.60476923,1.588495612,1.608421922,1.628622055,1.618224144,1.619284391,1.624693036,1.618678808,1.604282737,1.596675634
3,module4192,1.652584672,1.66634798,1.661535382,1.646724701,1.637596369,1.580028653,1.596682191,1.607276559,1.608465075,...,1.562722087,1.544186831,1.56231606,1.593993187,1.590831041,1.598883033,1.598778844,1.580049992,1.551323295,1.550339818
4,module2361,1.59260571,1.598946333,1.58533895,1.56410718,1.536944866,1.593787074,1.594391227,1.597786188,1.595568419,...,1.592455268,1.574870944,1.59363246,1.611418128,1.592223167,1.592243075,1.598004699,1.598522305,1.585622668,1.582370877

In [15]:
df5.head()

,low limit,1.05,1.05.1,1.05.2,1.05.3,1.05.4,1.05.5,1.05.6,1.05.7,1.05.8,...,1.05.40,1.05.41,1.05.42,1.05.43,1.05.44,1.05.45,1.05.46,1.05.47,1.05.48,1.05.49
0,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
1,barcode,PB,PC,PD,PE,PF,PG,PH,PI,PJ,...,PAP,PAQ,PAR,PAS,PAT,PAU,PAV,PAW,PAX,PAY
2,module3158,1.597673178,1.596551418,1.611853361,1.623739481,1.626957178,1.609759212,1.599552751,1.60321784,1.619698644,...,1.631358743,1.644104719,1.635082006,1.62251544,1.625540376,1.627163172,1.633051276,1.645643592,1.648587823,1.643083453
3,module9101,1.587428927,1.608364224,1.611225605,1.619310737,1.619567394,1.600398183,1.584273577,1.58857286,1.605104208,...,1.627970099,1.645436764,1.643384457,1.626332402,1.62373054,1.620441556,1.63503778,1.649520993,1.64633882,1.654895067
4,module2045,1.583381653,1.585923672,1.598855138,1.611401916,1.60985291,1.586651683,1.567066193,1.580392957,1.612032771,...,1.650094509,1.6703192,1.670483112,1.649427414,1.657798529,1.652893901,1.653319359,1.666705012,1.667273998,1.676305294

In [16]:
df6.head()

,low limit,1.05,1.05.1,1.05.2,1.05.3,1.05.4,1.05.5,1.05.6,1.05.7,1.05.8,...,1.05.60,1.05.61,1.05.62,1.05.63,1.05.64,1.05.65,1.05.66,1.05.67,1.05.68,1.05.69
0,high limit,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,...,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2,2.2
1,barcode,QB,QC,QD,QE,QF,QG,QH,QI,QJ,...,QBJ,QBK,QBL,QBM,QBN,QBO,QBP,QBQ,QBR,QBS
2,module9138,1.68803072,1.671784759,1.659208536,1.663386583,1.675576568,1.702787757,1.703445673,1.705212355,1.716116428,...,1.644232869,1.638100624,1.637249351,1.604166627,1.600101471,1.613740683,1.629603982,1.629444599,1.620921731,1.603893161
3,module9122,1.703558803,1.679965258,1.671675682,1.672392011,1.690542102,1.712445974,1.708434224,1.721238613,1.736963987,...,1.595143795,1.59408021,1.593248487,1.570883632,1.558725238,1.570076942,1.577320218,1.575303555,1.568512797,1.558322787
4,module848,1.558441281,1.547485471,1.54407239,1.543493867,1.545347214,1.56706357,1.56379509,1.555441022,1.562885165,...,1.643684864,1.638133287,1.636068702,1.629950523,1.630386591,1.630049586,1.635058045,1.639467597,1.638381481,1.636217117